### ISSUE TITLE
TypeError: Map#toJSON isn't generic

### ISSUE THREAD

**Issue by peteruithoven** [casperlamboo/plugin-worker#2]
When using the worker I get the following error when my code is being imported. 

```
TypeError: Map#toJSON isn't generic
```

This is probably caused because the `loads` property from `SystemJS.getConfig()` can't be stringified.

**Comment by casperlamboo** [comment]
Can only reproduce this error in a project with a relative large config, and only when there is no bundle created.

**Comment by casperlamboo** [comment]
@guybedford is it possible to omit the `loads` property from `SystemJS.getConfig()` in https://github.com/casperlamboo/plugin-worker/blob/master/src/loader-dev.js#L10 when passing it to the worker? I tried this and it solves this issue. I noticed the `loads` property is added after a `System.import` so I figured it is generated based on the existing config.

**Comment by guybedford** [comment]
Thanks, I've added https://github.com/systemjs/systemjs/commit/49f4566a4aefb07ed052affd9aa93455f7081374.

**Comment by casperlamboo** [comment]
Tried this and it works!
